---
version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain dependencies for leader Docker
- package-ecosystem: docker
  directory: /master
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain dependencies for agent Docker
- package-ecosystem: docker
  directory: /agent
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain dependencies for agent Docker
- package-ecosystem: npm
  directory: /webui/react/
  schedule:
    interval: daily
  allow:
    # Allow updates for React and any packages starting "react"
    - dependency-name: "react*"
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for main product
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for examples
- package-ecosystem: pip
  directory: /examples/tests
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for Model Hub
- package-ecosystem: pip
  directory: /model-hub/tests
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for docs
- package-ecosystem: pip
  directory: /docs
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for end-to-end tests
- package-ecosystem: pip
  directory: /e2e_tests/tests
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for harness tests
- package-ecosystem: pip
  directory: /harness/tests/requirements/requirements-harness.txt
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam

# Maintain python dependencies for harness tests
- package-ecosystem: pip
  directory: /harness/tests/requirements/requirements-cli.txt
  schedule:
    interval: daily
  #reviewers:
  #- determined-ai/someteam
