---
name: "Check Rebaseable"

############################################################
# Understand this security concern before you edit this file:
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
############################################################
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
      - 'master'
  pull_request_target: {}

jobs:
  check-rebaseable:
    runs-on: ubuntu-latest
    env:
      EE_REPO: determined-ai/determined-ee
      OSS_REPO: determined-ai/determined
    steps:
      - name: get EE
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # we only need the main branch
          token: ${{ secrets.DETERMINED_TOKEN }}
          repository: ${{ EE_REPO }}
      - name: add EE repository remote and get default branch
        run: |
          git remote add OSS github.com:${{ env.OSS_REPO }}
          git fetch OSS "${{ github.ref }}":proposed_base
      - name: attempt rebase
        run: |
          git rebase proposed_base
